name: End-to-end tests # 名字随你喜欢
on: [push, pull_request] # 表示 push 和 pull_request 动作时执行
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 步骤一，切出分支代码
        uses: actions/checkout@v1 # 使用社区现成的 action

      - name: Cypress run # 步骤二，运行 cypress
        uses: cypress-io/github-action@v1 # 使用官方提供的 action
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:1234

          # 以下几个参数可以把 test 记录到 cypress dashboard
          record: true # 开启记录
          parallel: true # 并行运行测试更快
          group: 'Actions example' # 组名称 随意
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}' # 这几个变量不用管
        env:
          # 传递 record key 到 CI 环境中
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # 发布到 GitHub page
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm run build